#!/usr/bin/env ruby
require 'rubygems'
require 'bundler'
Bundler.require

$:.unshift(File.expand_path("../../lib", __FILE__))

require 'chronatog/ey_integration'
require 'irb'

Chronatog::EyIntegration.setup!
IRB.start